// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Schendel_Week_10_Individual_Assignment.Models
{
    public partial class uspUpdateEmployeePersonalInfoResult
    {
    }
}
